services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: 3v3nTp@sSw0rD
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - devnet
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 10
  db-init:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - devnet
    environment:
      SQL_SERVER: sqlserver
      SQL_USER: sa
      SQL_PASSWORD: 3v3nTp@sSw0rD
      DB_NAME: EventBankingCo_CustomerService_Test
    volumes:
      - ./EventBankingCo.CustomerService.Database/bin/Output:/dacpac
      - ./init-db.sh:/init-db.sh
    working_dir: /src
    command: ["bash", "/init-db.sh"]

networks:
  devnet:
