name: Build and Deploy DACPAC to SQL Server

on:
  push:
    branches:
      - '**'

jobs:
  build-dacpac:
    name: Build DACPAC
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build DACPAC
        shell: pwsh
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" `
            "EventBankingCo.CustomerService.Database/EventBankingCo.CustomerService.Database.sqlproj" `
            /p:Configuration=Release `
            /p:Platform="Any CPU"

      - name: Upload DACPAC artifact
        uses: actions/upload-artifact@v4
        with:
          name: customer-service-dacpac
          path: dacpac/*.dacpac

  deploy-and-test:
    name: Deploy to SQL Server and Run Tests
    runs-on: ubuntu-latest
    needs: build-dacpac
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: Your!StrongP@ssw0rd123
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your!StrongP@ssw0rd123 -Q \"SELECT 1\"" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download DACPAC artifact
        uses: actions/download-artifact@v4
        with:
          name: customer-service-dacpac

      - name: Install sqlpackage
        run: |
          wget https://aka.ms/sqlpackage-linux -O sqlpackage.zip
          unzip sqlpackage.zip -d sqlpackage
          chmod +x sqlpackage/sqlpackage
          sudo mv sqlpackage/sqlpackage /usr/local/bin/sqlpackage

      - name: Wait for SQL Server to become available
        run: |
          for i in {1..30}; do
            /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your!StrongP@ssw0rd123 -Q "SELECT 1" && break
            echo "Waiting for SQL Server ($i)..."
            sleep 3
          done

      - name: Deploy DACPAC
        run: |
          sqlpackage \
            /Action:Publish \
            /SourceFile:customer-service.dacpac \
            /TargetServerName:localhost \
            /TargetDatabaseName:CustomerService \
            /TargetUser:sa \
            /TargetPassword:Your!StrongP@ssw0rd123

      - name: Run tests
        run: dotnet test
