name: Build, DACPAC Deploy, and Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: windows-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-20.04
        env:
          SA_PASSWORD: Your!StrongP@ssw0rd123
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --memory=3g
          --health-cmd="exit 0"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 2022

      - name: Wait for SQL Server to be ready
        shell: pwsh
        run: |
          Write-Host "Waiting for SQL Server to be ready..."
          $retries = 0
          while ($retries -lt 30) {
            try {
              sqlcmd -S localhost -U sa -P "Your!StrongP@ssw0rd123" -Q "SELECT 1"
              break
            } catch {
              Start-Sleep -Seconds 3
              $retries++
              Write-Host "Retrying SQL connection... ($retries)"
            }
          }

      - name: Build DACPAC
        run: |
          msbuild ./CustomerService/EventBankingCo.CustomerService.Database/EventBankingCo.CustomerService.Database.sqlproj /p:Configuration=Debug

      - name: Deploy DACPAC
        run: |
          & "C:\Program Files\Microsoft SQL Server\160\DAC\bin\SqlPackage.exe" /Action:Publish `
            /SourceFile:"CustomerService\EventBankingCo.CustomerService.Database\bin\Debug\EventBankingCo.CustomerService.Database.dacpac" `
            /TargetServerName:localhost `
            /TargetDatabaseName:CustomerService `
            /TargetUser:sa `
            /TargetPassword:"Your!StrongP@ssw0rd123"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --logger "trx"
